### PR TITLE
Fix titles when multiple links

### PR DESCRIPTION
**Pull request by yguedidi**

### CODE REVIEW

**Comment by stof** [comment]
you should add a test covering this to prevent regressions

**Comment by yguedidi** [comment]
@stof done

**Comment by stof** [comment]
@iamcal ping

**Comment by stof** [comment]
@iamcal ping again. any chance to merge this bugfix ?

**Comment by iamcal** [comment]
apologies for the incredible delay!

**Comment by yguedidi** [comment]
@iamcal Thank you! Can you please tag a new release?

**Comment by iamcal** [comment]
tagged as 1.7

**Pull request merged**
